In [1]:
import numpy as np 

x = np.array([[11, 28], [23, 84], [95, 56]]) 
print ("The array used for Integer Indexing")
print(x)

y = x[[0,1,2], [0,0,1]] 
print("The Output is:")
print(y) 

The array used for Integer Indexing
[[11 28]
 [23 84]
 [95 56]]
The Output is:
[11 23 56]


In [2]:
x = np.array([[11, 28], [23, 84], [95, 56]]) 
print ("The array used for Integer Indexing")
print(x)

y = x[[0,1,2], [0,0,1]] 
print("The Output is:")
print(y) 

The array used for Integer Indexing
[[11 28]
 [23 84]
 [95 56]]
The Output is:
[11 23 56]


In [3]:
x = np.array([[10, 81, 2], [3, 43, 35], [63, 72, 8], [92, 10, 11]]) 

# [10, 81, 2]
# [ 3, 43, 35]
# [62, 72, 8]
# [92, 10, 11]
# so corener elements are 10, 2, 92 and 11
   
print ('The array is:') 
print (x)

# picking the 1st and last row
rows = np.array([[0], [3]])
# picking 0 index and 2nd index element from each row
cols = np.array([[0, 2], [0, 2]])
y = x[rows, cols] 
   
print ('The corner elements of the array are:') 
print (y)

The array is:
[[10 81  2]
 [ 3 43 35]
 [63 72  8]
 [92 10 11]]
The corner elements of the array are:
[[10  2]
 [92 11]]


In [4]:
x = np.array([[11, 1, 12], [31, 4, 15], [6, 37, 8], [91, 10, 11]]) 

print("The array is:")
print(x)
# Using basic slicing
z = x[1:4, 1:3] 

print('After slicing the array becomes:')
print(z)

# using advanced indexing for column 
y = x[1:4, [1,2]] 

print('After Slicing using advance index for column:')
print(y)

The array is:
[[11  1 12]
 [31  4 15]
 [ 6 37  8]
 [91 10 11]]
After slicing the array becomes:
[[ 4 15]
 [37  8]
 [10 11]]
After Slicing using advance index for column:
[[ 4 15]
 [37  8]
 [10 11]]


In [5]:
#BOOLEAN indexing

x = np.array([[11, 51, 2],[23, 24, 5], [16, 47, 8] ,[91, 10, 11]]) 

print("The array is:")
print(x)

# Now we will print the items greater than 11
print("The items greater than 11 are:")
print(x[x>11])

The array is:
[[11 51  2]
 [23 24  5]
 [16 47  8]
 [91 10 11]]
The items greater than 11 are:
[51 23 24 16 47 91]


In [6]:
a = np.array([np.nan, 1, 12, np.nan, 3, 41, 54]) 

print("After omitting NaN the output array is :")
print (a[~np.isnan(a)])

After omitting NaN the output array is :
[ 1. 12.  3. 41. 54.]


In [7]:

a = np.array([1, 2+6j, 5, 3.5+5j]) 

print("After Filtering the non-complex numbers :")
print (a[np.iscomplex(a)])

After Filtering the non-complex numbers :
[2. +6.j 3.5+5.j]
