In [1]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([2,7,8,9])
c = a+b;
print(c)

[ 3  9 11 13]


In [2]:
a = np.array([4,5,6,7])  
b = np.array([1,3,5,7,9,11,14])  
c = a+b;  
print(c) 

ValueError: operands could not be broadcast together with shapes (4,) (7,) 

In [3]:
import numpy as np  

a = np.array([[1,2,3,4],[11,10,8,6],[10,20,39,3]])  
b = np.array([4,8,10,12])
  
print("\n The array a is :")  
print(a)  
print("\n The array b is :")  
print(b)  

print("\n After addition of array a and b resultant array is:")  
c = a + b;  
print(c)  


 The array a is :
[[ 1  2  3  4]
 [11 10  8  6]
 [10 20 39  3]]

 The array b is :
[ 4  8 10 12]

 After addition of array a and b resultant array is:
[[ 5 10 13 16]
 [15 18 18 18]
 [14 28 49 15]]


In [4]:
#Rules for NumPy Broadcasting

#    The concept of broadcasting in NumPy is only possible if the following cases are satisfied:

#         1.The smaller dimension ndarray can be appended with '1' in its shape.

#         2.The size of each output dimension should be the maximum of the input sizes in the dimension.

#         3.It is important to note that input can be used in the calculation only if its size in a particular dimension matches the output size or its value is exactly 1.

#         4.Suppose the input size is 1, then the first data entry should be used for the calculation along the dimension.

#     The concept of broadcasting in NumPy can be applied to the arrays only if the following rules are satisfied.

#         1.All the arrays in the input must have the same shape.

#         2.Arrays having the same number of dimensions, and the length of each dimension is either a common length or 1.

#         3.Those arrays with the fewer dimension can be appended with '1' in its shape.
