In [8]:
import numpy as np

a = np.arange(0,40,5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [13]:
np.shape(a)
a = a.reshape(2, 4)

In [21]:
print("Iterating over the array:")   
for x in np.nditer(a):  
    print(x, end=' ') 
a = a.T
print("\nIterating over the array:")   
for x in np.nditer(a):  
    print(x, end=' ') 

Iterating over the array:
0 5 10 15 20 25 30 35 
Iterating over the array:
0 5 10 15 20 25 30 35 

In [15]:
a = np.arange(0,40,5)

print ("The Original array is:")
print (a)
print ('\n')

# showing elements of array one by one
print ("The Modified array is:")
for x in np.nditer(a):
    print(x)

The Original array is:
[ 0  5 10 15 20 25 30 35]


The Modified array is:
0
5
10
15
20
25
30
35


In [2]:
import numpy as np  
a = np.array([[1,2,3,4],[8,9,5,6],[10,20,29,31]])  
print("\nPrinting the array:\n")  
print(a)  
print("\nPrinting the transpose of the array:\n")  
at = a.T  
print(at)  
print("\nIterating over the transposed array\n")  
  
for x in np.nditer(at):  
    print(x, end= ' ')  
print("\nSorting the transposed array in C-style:\n")  
c = at.copy(order = 'C')  
print(c)  
  
print("\nIterating over the C-style array:\n")  
for x in np.nditer(c):  
    print(x, end=' ')  
      
d = at.copy(order = 'F')  
print("\n")
print(d) 

print("\nIterating over the F-style array:\n")  
for x in np.nditer(d):  
    print(x, end=' ')  


Printing the array:

[[ 1  2  3  4]
 [ 8  9  5  6]
 [10 20 29 31]]

Printing the transpose of the array:

[[ 1  8 10]
 [ 2  9 20]
 [ 3  5 29]
 [ 4  6 31]]

Iterating over the transposed array

1 2 3 4 8 9 5 6 10 20 29 31 
Sorting the transposed array in C-style:

[[ 1  8 10]
 [ 2  9 20]
 [ 3  5 29]
 [ 4  6 31]]

Iterating over the C-style array:

1 8 10 2 9 20 3 5 29 4 6 31 

[[ 1  8 10]
 [ 2  9 20]
 [ 3  5 29]
 [ 4  6 31]]

Iterating over the F-style array:

1 2 3 4 8 9 5 6 10 20 29 31 

In [4]:
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

print ('The First array :') 
print (a)
print ('\n')

print ('The Second array is') 
b = np.array([1, 2, 3, 4], dtype = int) 
print (b)  
print ('\n' )

print ('The Modified array is') 
for x,y in np.nditer([a,b]): 
    print ("%d:%d" %(x,y))
    print (x,":",y)

The First array :
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


The Second array is
[1 2 3 4]


The Modified array is
0:1
0 : 1
5:2
5 : 2
10:3
10 : 3
15:4
15 : 4
20:1
20 : 1
25:2
25 : 2
30:3
30 : 3
35:4
35 : 4
40:1
40 : 1
45:2
45 : 2
50:3
50 : 3
55:4
55 : 4


In [5]:

a = np.arange(0,50,6)
a = a.reshape(3,3)
print ('The Original array is:')
print (a)
print ('\n')
for x in np.nditer(a, op_flags = ['readwrite']):
    # modifying the value of array elements
    x[...] = 2+x
print ('The Modified array is:')
print (a)

The Original array is:
[[ 0  6 12]
 [18 24 30]
 [36 42 48]]


The Modified array is:
[[ 2  8 14]
 [20 26 32]
 [38 44 50]]


In [6]:
a = a + 2

In [7]:
a

array([[ 4, 10, 16],
       [22, 28, 34],
       [40, 46, 52]])