In [1]:
import numpy as np  

a = np.array([[11,2,23],[14,75,6],[17,8,9]], ndmin=3) 
print("A is:\n",a)

b = np.array([[9,8,7],[6,5,4],[3,2,1]], ndmin=3)    
print("B is:\n",b)

out = np.multiply(a,b)  
print("The resultant matrix is :")
print(out)

A is:
 [[[11  2 23]
  [14 75  6]
  [17  8  9]]]
B is:
 [[[9 8 7]
  [6 5 4]
  [3 2 1]]]
The resultant matrix is :
[[[ 99  16 161]
  [ 84 375  24]
  [ 51  16   9]]]


In [2]:
import numpy as np

A = np.array([[1,2,3], [4,5,6],[1,2,1]])
B = np.array([[1,1,1], [0,1,0], [1,1,1]])

print("Matrix A is:\n",A)
print("Matrix A is:\n",B)

C = np.matmul(A,B)
print("The Matrix multiplication of matrix A and B is:\n",C)


Matrix A is:
 [[1 2 3]
 [4 5 6]
 [1 2 1]]
Matrix A is:
 [[1 1 1]
 [0 1 0]
 [1 1 1]]
The Matrix multiplication of matrix A and B is:
 [[ 4  6  4]
 [10 15 10]
 [ 2  4  2]]


In [3]:
import numpy.matlib 
import numpy as np 

a = [[1,4],[2,1]] 
print("A is",a)
b = [1,2]
print("B is",b)
print("AxB is")
print(np.matmul(a,b))
print("BxA is ")
print (np.matmul(b,a))

A is [[1, 4], [2, 1]]
B is [1, 2]
AxB is
[9 4]
BxA is 
[5 6]


In [4]:
import numpy as np

A = np.array([7,9,8])
B = np.array([2,5,6])
print("Matrix A is:\n", A)
print("Matrix A is:\n", B)

C = np.dot(A,B)
print("Dot product of matrix A and B is:\n", C)

Matrix A is:
 [7 9 8]
Matrix A is:
 [2 5 6]
Dot product of matrix A and B is:
 107


In [5]:
import numpy as np

A = np.array([[1,4],[3,1]])
B = np.array([[4,5],[6,5]])
print("Matrix A is:\n", A)
print("Matrix A is:\n", B)

C = np.dot(A, B)
print("Matrix multiplication of matrix A and B is:\n", C)

Matrix A is:
 [[1 4]
 [3 1]]
Matrix A is:
 [[4 5]
 [6 5]]
Matrix multiplication of matrix A and B is:
 [[28 25]
 [18 20]]


In [6]:
A = np.array([[2,4],[3,5]])
print("Matrix A is:\n", A)
C = np.dot(3, A)
print("Matrix multiplication of matrix A with scalar :\n", C)

Matrix A is:
 [[2 4]
 [3 5]]
Matrix multiplication of matrix A with scalar :
 [[ 6 12]
 [ 9 15]]
