In [1]:
import numpy as np 

a = np.arange(10) 
print("The ndarray is :")
print(a)

s = slice(2,7,2) 
print("After applying slice() Function:")
print (a[s])

The ndarray is :
[0 1 2 3 4 5 6 7 8 9]
After applying slice() Function:
[2 4 6]


In [2]:
a = np.arange(15)
print("The array is :")
print(a)
# using the index directly
b = a[7] 
print("The Eighth item in the array is :")
print (b)

The array is :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
The Eighth item in the array is :
7


In [1]:
import numpy as np
 
a = np.arange(20) 
print("The array is :");
print(a)

print("Slicing of items starting from the index:")
print (a[2:])

The array is :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Slicing of items starting from the index:
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [2]:

 
a = np.arange(20) 
print("The array is :");
print(a)

print("Slicing of items starting from the index:")
print (a[2:8])

The array is :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Slicing of items starting from the index:
[2 3 4 5 6 7]


In [3]:
a = np.array([[11,2,23],[33,44,5],[84,25,16]]) 

print ("The array is :") 
print (a )
print ('\n')

#To return array of items in the second column 
print ('The items in the second column are:')  
print (a[..., 1] )
print ('\n')

# In order to slice all items from the second row 
print ('The items in the second row are:') 
print (a[1, ...])
print ('\n') 

# In order to slice all items from column 1 onwards 
print ('The items onwards to column 1 are:' )
print (a[..., 1:])

The array is :
[[11  2 23]
 [33 44  5]
 [84 25 16]]


The items in the second column are:
[ 2 44 25]


The items in the second row are:
[33 44  5]


The items onwards to column 1 are:
[[ 2 23]
 [44  5]
 [25 16]]
