In [2]:
import numpy as np 
#Array Creation - Empty, Zeroes and Ones
# an array with 4 rows and 3 columns. elements in an array will show random values because they are not initialized:
x = np.empty([4,3], dtype = int) 
print (x)

[[    140327880530912     140327880530912                   0]
 [                  0     310449269446508 1976261564417966948]
 [1181072730309598042 1397245512428821356     312648326256492]
 [2120376752527377252 1541360700499238234     314847383066476]]


In [11]:
arr = np.zeros((3,3), dtype = int)  
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [12]:
arr = np.ones((3,3), dtype = int)  
print(arr)  

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [13]:
#Python NumPy Array Creation using existing data

# python tuple
l = (34,7,8,78)
# creating array using the tuple
a = np.asarray(l)

print(type(a))  
print(a)  

<class 'numpy.ndarray'>
[34  7  8 78]


In [47]:
# python list
l = [[1,2,3],[8,9],[5,7]] 
# creating array from list 
b = np.asarray(l)
print(b)
print(type(b))
print(b.dtype)  
print(b.shape)

[list([1, 2, 3]) list([8, 9]) list([5, 7])]
<class 'numpy.ndarray'>
object
(3,)


In [45]:
# intialize bytes
l = b'StudyTonight!'  
print(type(l))  

a = np.frombuffer(l, dtype = "S1")  
print(a)  
print(type(a))  

<class 'bytes'>
[b'S' b't' b'u' b'd' b'y' b'T' b'o' b'n' b'i' b'g' b'h' b't' b'!']
<class 'numpy.ndarray'>


In [3]:
# using python tuple
tup = (2,4,6,20)  
# create an iterator
it = iter(tup)  

# create ndarray using the iterator
x = np.fromiter(it, dtype = float)  

print(x)  
print(type(x)) 

[ 2.  4.  6. 20.]
<class 'numpy.ndarray'>


In [4]:
x = np.arange(15) 
print (x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [5]:
arr = np.arange(0,10,2,complex)  
print(arr) 

[0.+0.j 2.+0.j 4.+0.j 6.+0.j 8.+0.j]


In [6]:
# start=20, end=30, num=5
arr = np.linspace(20, 30, 5)  
print("The array in this range is ",arr)  

The array in this range is  [20.  22.5 25.  27.5 30. ]


In [7]:

x = np.linspace(2,4,5, retstep = True) 
print (x)

(array([2. , 2.5, 3. , 3.5, 4. ]), 0.5)


In [8]:
a = np.logspace(20, 30, num = 5, endpoint = True)  
print("The array will be",a)  

The array will be [1.00000000e+20 3.16227766e+22 1.00000000e+25 3.16227766e+27
 1.00000000e+30]


In [9]:
arr = np.logspace(5, 30, num = 5,base = 3, endpoint = True)  
print("The array is: ",arr) 

The array is:  [2.43000000e+02 2.33138563e+05 2.23677324e+08 2.14600041e+11
 2.05891132e+14]
