In [1]:
# Various Sorting Algorithms

# Various sorting algorithms along with their properties that are used are as given below:
# Serial No. 	Kind 	Worst case Complexity 	Speed 	Stable 	Work Space
# 1. 	'quicksort' 	O(n^2) 	1 	No 	0
# 2. 	'heapsort' 	O(n*log(n)) 	3 	No 	0
# 3. 	'mergesort' 	O(n*log(n)) 	2 	Yes 	-n/2
# 4. 	'timsort' 	O(n*log(n)) 	2 	Yes 	-n/2



In [6]:
import numpy as np 

# sorting along the first axis
a = np.array([[17, 15], [10, 25]]) 
print ("a : \n")
print (a)
arr1 = np.sort(a, axis = 0)
print ("Sorting Along first axis : \n")
print(arr1)

# sorting along the last axis 
b = np.array([[1, 15], [20, 18]]) 
print ("b : \n")
print (b)
arr2 = np.sort(b, axis = -1) 
print ("\nSorting along last axis : \n")
print(arr2) 


c = np.array([[12, 15], [10, 1]]) 
print ("c : \n")
print (c)
arr3 = np.sort(c, axis = None) 
print ("\nSorting Along none axis : \n")
print(arr3) 

a : 

[[17 15]
 [10 25]]
Sorting Along first axis : 

[[10 15]
 [17 25]]
b : 

[[ 1 15]
 [20 18]]

Sorting along last axis : 

[[ 1 15]
 [18 20]]
c : 

[[12 15]
 [10  1]]

Sorting Along none axis : 

[ 1 10 12 15]


In [11]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]

values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),

          ('Galahad', 1.7, 38)]

a = np.array(values, dtype=dtype)       # create a structured array

a1= np.sort(a, order='height')                        

print(a1)
# Sort by age, then height if ages are equal:

a2= np.sort(a, order=['age', 'height'])     
print(a2)

[(b'Galahad', 1.7, 38) (b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38)]
[(b'Galahad', 1.7, 38) (b'Lancelot', 1.9, 38) (b'Arthur', 1.8, 41)]
