In [1]:
import numpy as np



In [41]:
a = np.array([[[[1,2,0],[1,3,0]],[[2,2,0],[2,3,0]]],[[[1,2,0],[1,3,0]],[[2,2,0],[2,3,0]]]], dtype = (int,int))

In [38]:
a.ndim

4

In [39]:
a

array([[[[1, 2, 0],
         [1, 3, 0]],

        [[2, 2, 0],
         [2, 3, 0]]],


       [[[1, 2, 0],
         [1, 3, 0]],

        [[2, 2, 0],
         [2, 3, 0]]]])

In [10]:
a = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]], [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]], [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]], [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]])


In [32]:
a

array([[[[0, 2, 3, 4],
         [2, 4, 3, 3]],

        [[0, 2, 3, 4],
         [2, 4, 3, 6]],

        [[0, 2, 3, 8],
         [2, 4, 3, 9]]],


       [[[0, 2, 3, 4],
         [2, 4, 3, 3]],

        [[0, 2, 3, 4],
         [2, 4, 3, 6]],

        [[0, 2, 3, 8],
         [2, 4, 3, 9]]]])

In [31]:
a = np.array([[[[0,2,3,4],[2,4,3,3]],[[0,2,3,4],[2,4,3,6]],[[0,2,3,8],[2,4,3,9]]],[[[0,2,3,4],[2,4,3,3]],[[0,2,3,4],[2,4,3,6]],[[0,2,3,8],[2,4,3,9]]]])

a.ndim

4

In [51]:
    a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

    a = np.expand_dims(a, axis=0)
    print (a)

    a = np.repeat(a, 4, axis=0)
    a[0][1][1][2]

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]]]


12

In [47]:
a
a[1,1,1,1]

11

In [53]:
type(a.shape)

tuple

In [60]:
a.shape[-2:]
a

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]]])

In [101]:
x = np.argwhere(a==11)
x

array([[0, 1, 1, 1],
       [1, 1, 1, 1],
       [2, 1, 1, 1],
       [3, 1, 1, 1]])

In [93]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
b
y = np.argwhere(b==2)

In [98]:
y[]

array([0, 0, 1])

In [97]:
b[1]

array([[ 7,  8,  9],
       [10, 11, 12]])