In [2]:
import numpy as np

a=np.arange(start=2, stop=12, step=2)
print("The Output is :",a)

a=np.arange(start=2, stop=12)
print("The Output is :",a)


a=np.arange(12)
print("The Output is :",a)

a=np.arange(-10, -1)
print("The output is:")
print(a)



The Output is : [ 2  4  6  8 10]
The Output is : [ 2  3  4  5  6  7  8  9 10 11]
The Output is : [ 0  1  2  3  4  5  6  7  8  9 10 11]
The output is:
[-10  -9  -8  -7  -6  -5  -4  -3  -2]


In [3]:
import numpy as np

a = np.arange(12) 
print("The Original array : \n", a) 

# shaping the array with 2 rows and 4 columns 
a1= np.arange(12).reshape(2, 6) 
print("\n The reshaped array with 2 rows and 6 columns : \n", a1) 

# shaping the array with 4 rows and 2 columns 
a2 = np.arange(12).reshape(6,2) 
print("\n The reshaped array with 6 rows and 2 columns : \n", a2) 

# Construction of a 3D array 
a3 = np.arange(12).reshape(2, 3, 2) 
print("\nAfter reshaping the original array to 3D : \n", a3) 


The Original array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 The reshaped array with 2 rows and 6 columns : 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

 The reshaped array with 6 rows and 2 columns : 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

After reshaping the original array to 3D : 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [4]:
import numpy as np  

x = np.arange(12)  
print("The array is :\n",x)
y = np.reshape(x, (4, 3), order='F')  
print("Reshaping the original array using F-like index ordering")
print(y)

The array is :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaping the original array using F-like index ordering
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
