In [10]:
import numpy as np 
#Array Creation - Empty, Zeroes and Ones
# an array with 4 rows and 3 columns. elements in an array will show random values because they are not initialized:
x = np.empty([4,3], dtype = int) 
print (x)

[[    140354463165408     140354463165408      18081812316388]
 [-976718169184964096       1092834295808    6317793813209714]
 [8214565720935235584      38972533243925  608548899666227712]
 [        31977373696   29680216880196722 8214565720952012800]]


In [11]:
arr = np.zeros((3,3), dtype = int)  
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [12]:
arr = np.ones((3,3), dtype = int)  
print(arr)  

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [13]:
#Python NumPy Array Creation using existing data

# python tuple
l = (34,7,8,78)
# creating array using the tuple
a = np.asarray(l)

print(type(a))  
print(a)  

<class 'numpy.ndarray'>
[34  7  8 78]


In [47]:
# python list
l = [[1,2,3],[8,9],[5,7]] 
# creating array from list 
b = np.asarray(l)
print(b)
print(type(b))
print(b.dtype)  
print(b.shape)

[list([1, 2, 3]) list([8, 9]) list([5, 7])]
<class 'numpy.ndarray'>
object
(3,)


In [45]:
# intialize bytes
l = b'StudyTonight!'  
print(type(l))  

a = np.frombuffer(l, dtype = "S1")  
print(a)  
print(type(a))  

<class 'bytes'>
[b'S' b't' b'u' b'd' b'y' b'T' b'o' b'n' b'i' b'g' b'h' b't' b'!']
<class 'numpy.ndarray'>
