In [1]:
import pandas as pd


In [2]:
pd.__version__

'1.2.4'

In [3]:
A = pd.Series([2,3,4,5], index = ['a','b','c','d'])

In [4]:
A.values

array([2, 3, 4, 5])

In [6]:
type(A.values)

numpy.ndarray

In [7]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [9]:
A['a':'c']

a    2
b    3
c    4
dtype: int64

In [10]:
grades_dict = {'A':4,'A-':3,'B':3,'B-':2.5,'B':2}
grades = pd.Series(grades_dict)

In [11]:
grades


A     4.0
A-    3.0
B     2.0
B-    2.5
dtype: float64

In [12]:
grades.values

array([4. , 3. , 2. , 2.5])

In [13]:
grades['A']

4.0

In [14]:
grades[0:2]

A     4.0
A-    3.0
dtype: float64

In [15]:
marks_dict = {'A':85, 'A-':80, 'B-':70, 'B':65}
marks = pd.Series(marks_dict)

In [16]:
D = pd.DataFrame({'Marks':marks, 'Grades':grades})

In [17]:
D

Marks  Grades
A      85     4.0
A-     80     3.0
B      65     2.0
B-     70     2.5

In [18]:
D.T

A    A-     B    B-
Marks   85.0  80.0  65.0  70.0
Grades   4.0   3.0   2.0   2.5

In [19]:
D.values

array([[85. ,  4. ],
       [80. ,  3. ],
       [65. ,  2. ],
       [70. ,  2.5]])

In [20]:
D.keys

<bound method NDFrame.keys of     Marks  Grades
A      85     4.0
A-     80     3.0
B      65     2.0
B-     70     2.5>

In [21]:
D.columns


Index(['Marks', 'Grades'], dtype='object')

In [22]:
D['Marks']

A     85
A-    80
B     65
B-    70
Name: Marks, dtype: int64

In [25]:
D['ScaledMarks'] = D['Marks']*90/100

In [26]:
D

Marks  Grades  ScaledMarks
A      85     4.0         76.5
A-     80     3.0         72.0
B      65     2.0         58.5
B-     70     2.5         63.0

In [44]:
G = D[D['Marks']>70]

In [45]:
G

Marks  Grades  ScaledMarks
A      85     4.0         76.5
A-     80     3.0         72.0

In [49]:
G['Marks'].values 

array([85, 80])

In [50]:
G

Marks  Grades  ScaledMarks
A      85     4.0         76.5
A-     80     3.0         72.0

In [51]:
D

Marks  Grades  ScaledMarks
A      85     4.0         76.5
A-     80     3.0         72.0
B      65     2.0         58.5
B-     70     2.5         63.0

In [52]:
A = pd.Series(['a','b','c'],index = [1,3,5])

In [53]:
A[1]

'a'

In [54]:
A[1:3]

3    b
5    c
dtype: object

In [55]:
A.loc[1:3]

1    a
3    b
dtype: object

In [56]:
A.iloc[1:3]

3    b
5    c
dtype: object

In [57]:
#pd.fillna()
#pd.dropna()


In [58]:
D

Marks  Grades  ScaledMarks
A      85     4.0         76.5
A-     80     3.0         72.0
B      65     2.0         58.5
B-     70     2.5         63.0

In [59]:
D.iloc[2,:]

Marks          65.0
Grades          2.0
ScaledMarks    58.5
Name: B, dtype: float64

In [61]:
D.iloc[::-1,:]

Marks  Grades  ScaledMarks
B-     70     2.5         63.0
B      65     2.0         58.5
A-     80     3.0         72.0
A      85     4.0         76.5